repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black week1
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort week1
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 week1
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: pytest week1
        language: system
        pass_filenames: false